name: Vendo arquivos compartilhados entre Jobs

on:
  push:
    branches:
        - main

jobs:
    job_1:
      runs-on: ubuntu-latest
      steps:
        - name: Confere versao do Ubuntu
          run: cat /etc/os-release

        - name: Exibir uma mensagem
          run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > mensagem.txt

    job_2:
      runs-on: ubuntu-latest
      steps:
        - name: Qualquer outra coisa
          run: ls -lha

        - name: Le conteudo do arquivo
          run: cat mensagem.txt