name: Vendo arquivos compartilhados entre Jobs

on:
  workflow_dispatch

jobs:
    job_1:
      runs-on: ubuntu-latest
      steps:
        - name: Confere versao do Ubuntu
          run: cat /etc/os-release

        - name: Exibir uma mensagem
          run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > ${{ github.workspace }}/mensagem.txt

               # owner/repo@ref - Comum
               # owner/repo/aws@ref - Comum
 
               # owner/repo/ecs-login.yml@ref - N達o t達o comum
               # owner/repo/aws/ecs-login.yml@ref - N達o t達o comum
               
        - uses: actions/upload-artifact@v4
          with:
            name: strigus-upload
            path: ${{ github.workspace }}/mensagem.txt

    job_2:
      runs-on: ubuntu-latest
      needs: job_1
      steps:
        - name: Ver o conteudo do diretorio
          run: ls -lha

        - uses: actions/download-artifact@v4
          with:
            name: strigus-upload
            path: strigus

        - name: Ver o conteudo do diretorio
          run: ls -lha && ls ./strigus/

        - name: Acessa arquivo mensagem
          run: mv strigus/mensagem.txt . && rm -rf ./strigus

        - name: Ver o conteudo do diretorio
          run: ls -lha

        - name: Le conteudo do arquivo
          run: cat mensagem.txt